name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: [8.0.27, 8.1.14, 8.2.1]

    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@87cc7c2f65e10e0e64be54a3e41a62a4c61bd1a9
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
